[features]
seeds = false
[programs.localnet]
solos = "Z8L5or7nVJEZvZ5T7XuKrAG1SWSTLW7x3tp158TYRhy"
solos_strategy = "E1eeAWjEGqfH1CQ1SAtsnnuwwoJyrswjjboEwGLg8eG4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/armariya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
